### ISSUE TITLE
No expiration

### ISSUE THREAD

**Issue by ngocdiem138** [directa24/cashin-java-sdk#4]
https://github.com/directa24/cashin-java-sdk/blob/f0842f328b592259a43f5460b3e90b44312fb87c/src/main/java/com/directa24/model/request/CreateDepositRequest.java#L24
I see expiration fields, but I don't know how to set the expiration for the CreateDepositRequest.
![image](https://github.com/directa24/cashin-java-sdk/assets/89444580/eb155cad-0e43-40f2-beee-9145f80d4943)

**Comment by directa24** [comment]
Hi @ngocdiem138 . The expiration field was added. We make a new public release with version 1.0.19.
Thanks for your comment!

**Comment by directa24** [comment]
Closing Issue
